#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Sep 16 14:23:00 2021

@author: Claire He

Traitement de la base updatée
"""

import pandas as pd
import numpy as np

file_path ='/Users/h2jw/Documents/GitHub/NLP-FOMC/scrapping/df_statement_real.csv'

df = pd.read_csv(file_path, low_memory=True)
    

### ADDITIONAL BY-HAND NEEDED CLEANING 
# scrapping integrates cleaning, however exceptions not handled are : 
# - when a word is separated between pdf/txt conversion, it is not reconstructed automatically
# - subsistance of capital letters - extra duplicate from the interlocutor's name in particular
# with the case of VICE CHAIRMAN DUDLEY ??



















